
package au.net.electronichealth.ns.pcehr.svc.getindividualdetailsview._2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getIndividualDetailsViewService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/GetIndividualDetailsView/2.0", wsdlLocation = "wsdl/B2B_GetIndividualDetailsView.wsdl")
public class GetIndividualDetailsViewService
    extends Service
{

    private final static URL GETINDIVIDUALDETAILSVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETINDIVIDUALDETAILSVIEWSERVICE_EXCEPTION;
    private final static QName GETINDIVIDUALDETAILSVIEWSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/svc/GetIndividualDetailsView/2.0", "getIndividualDetailsViewService");

    static {
        GETINDIVIDUALDETAILSVIEWSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.pcehr.svc.getindividualdetailsview._2.GetIndividualDetailsViewService.class.getResource("wsdl/B2B_GetIndividualDetailsView.wsdl");
        WebServiceException e = null;
        if (GETINDIVIDUALDETAILSVIEWSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_GetIndividualDetailsView.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETINDIVIDUALDETAILSVIEWSERVICE_EXCEPTION = e;
    }

    public GetIndividualDetailsViewService() {
        super(__getWsdlLocation(), GETINDIVIDUALDETAILSVIEWSERVICE_QNAME);
    }

    public GetIndividualDetailsViewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETINDIVIDUALDETAILSVIEWSERVICE_QNAME, features);
    }

    public GetIndividualDetailsViewService(URL wsdlLocation) {
        super(wsdlLocation, GETINDIVIDUALDETAILSVIEWSERVICE_QNAME);
    }

    public GetIndividualDetailsViewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETINDIVIDUALDETAILSVIEWSERVICE_QNAME, features);
    }

    public GetIndividualDetailsViewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetIndividualDetailsViewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetIndividualDetailsViewPortType
     */
    @WebEndpoint(name = "getIndividualDetailsViewSOAP12Port")
    public GetIndividualDetailsViewPortType getGetIndividualDetailsViewSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetIndividualDetailsView/2.0", "getIndividualDetailsViewSOAP12Port"), GetIndividualDetailsViewPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetIndividualDetailsViewPortType
     */
    @WebEndpoint(name = "getIndividualDetailsViewSOAP12Port")
    public GetIndividualDetailsViewPortType getGetIndividualDetailsViewSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetIndividualDetailsView/2.0", "getIndividualDetailsViewSOAP12Port"), GetIndividualDetailsViewPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETINDIVIDUALDETAILSVIEWSERVICE_EXCEPTION!= null) {
            throw GETINDIVIDUALDETAILSVIEWSERVICE_EXCEPTION;
        }
        return GETINDIVIDUALDETAILSVIEWSERVICE_WSDL_LOCATION;
    }

}
