
package ihe.iti.xds_b._2007;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.PCEHRHeader;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.Signature;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.Timestamp;
import oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentRepository_PortType", targetNamespace = "urn:ihe:iti:xds-b:2007")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.ObjectFactory.class,
    ihe.iti.xds_b._2007.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.lcm._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.query._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class,
    pcehr_override.org.w3.ObjectFactory.class
})
public interface DocumentRepositoryPortType {


    /**
     * 
     * @param pcehrHeader
     * @param timestampHeader
     * @param parameters
     * @param signatureHeader
     * @return
     *     returns oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponseType
     */
    @WebMethod(operationName = "DocumentRepository_ProvideAndRegisterDocumentSet-b")
    @WebResult(name = "RegistryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0", partName = "parameters")
    public RegistryResponseType documentRepositoryProvideAndRegisterDocumentSetB(
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "timestampHeader")
        Timestamp timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<Signature> signatureHeader,
        @WebParam(name = "PCEHRHeader", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "PCEHRHeader")
        PCEHRHeader pcehrHeader,
        @WebParam(name = "ProvideAndRegisterDocumentSetRequest", targetNamespace = "urn:ihe:iti:xds-b:2007", partName = "parameters")
        ProvideAndRegisterDocumentSetRequest parameters);

    /**
     * 
     * @param pcehrHeader
     * @param timestampHeader
     * @param parameters
     * @param signatureHeader
     * @return
     *     returns ihe.iti.xds_b._2007.RetrieveDocumentSetResponse
     */
    @WebMethod(operationName = "DocumentRepository_RetrieveDocumentSet")
    @WebResult(name = "RetrieveDocumentSetResponse", targetNamespace = "urn:ihe:iti:xds-b:2007", partName = "parameters")
    public RetrieveDocumentSetResponse documentRepositoryRetrieveDocumentSet(
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "timestampHeader")
        Timestamp timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<Signature> signatureHeader,
        @WebParam(name = "PCEHRHeader", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "PCEHRHeader")
        PCEHRHeader pcehrHeader,
        @WebParam(name = "RetrieveDocumentSetRequest", targetNamespace = "urn:ihe:iti:xds-b:2007", partName = "parameters")
        RetrieveDocumentSetRequest parameters);

}
