
package au.net.electronichealth.ns.pcehr.b2b.svc.pcehrprofile._1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PCEHRProfileService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", wsdlLocation = "wsdl/B2B_PCEHRProfile.wsdl")
public class PCEHRProfileService
    extends Service
{

    private final static URL PCEHRPROFILESERVICE_WSDL_LOCATION;
    private final static WebServiceException PCEHRPROFILESERVICE_EXCEPTION;
    private final static QName PCEHRPROFILESERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", "PCEHRProfileService");

    static {
        PCEHRPROFILESERVICE_WSDL_LOCATION = au.net.electronichealth.ns.pcehr.b2b.svc.pcehrprofile._1.PCEHRProfileService.class.getResource("wsdl/B2B_PCEHRProfile.wsdl");
        WebServiceException e = null;
        if (PCEHRPROFILESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_PCEHRProfile.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PCEHRPROFILESERVICE_EXCEPTION = e;
    }

    public PCEHRProfileService() {
        super(__getWsdlLocation(), PCEHRPROFILESERVICE_QNAME);
    }

    public PCEHRProfileService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCEHRPROFILESERVICE_QNAME, features);
    }

    public PCEHRProfileService(URL wsdlLocation) {
        super(wsdlLocation, PCEHRPROFILESERVICE_QNAME);
    }

    public PCEHRProfileService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCEHRPROFILESERVICE_QNAME, features);
    }

    public PCEHRProfileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PCEHRProfileService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PCEHRProfilePortType
     */
    @WebEndpoint(name = "PCEHRProfileSOAP12Port")
    public PCEHRProfilePortType getPCEHRProfileSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", "PCEHRProfileSOAP12Port"), PCEHRProfilePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PCEHRProfilePortType
     */
    @WebEndpoint(name = "PCEHRProfileSOAP12Port")
    public PCEHRProfilePortType getPCEHRProfileSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", "PCEHRProfileSOAP12Port"), PCEHRProfilePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCEHRPROFILESERVICE_EXCEPTION!= null) {
            throw PCEHRPROFILESERVICE_EXCEPTION;
        }
        return PCEHRPROFILESERVICE_WSDL_LOCATION;
    }

}
