
package au.net.electronichealth.ns.pcehr.svc.getview._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.PCEHRHeader;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.Signature;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.Timestamp;
import au.net.electronichealth.ns.pcehr.xsd.interfaces.getview._1.GetView;
import au.net.electronichealth.ns.pcehr.xsd.interfaces.getview._1.GetViewResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetViewPortType", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.getview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.diagnosticimagingreportview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.healthrecordoverview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.pathologyreportview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.healthcheckscheduleview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.medicareoverview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.observationview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.prescriptionanddispenseview._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.view.viewcommontype._1.ObjectFactory.class,
    au.net.electronichealth.ns.wsp.xsd.standarderror._2010.ObjectFactory.class,
    pcehr_override.org.w3.ObjectFactory.class
})
public interface GetViewPortType {


    /**
     * 
     * @param pcehrHeader
     * @param parameters0
     * @param timestampHeader
     * @param parameters
     * @param signatureHeader
     * @throws StandardErrorMsg
     */
    @WebMethod
    @Action(input = "http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0/GetViewPortType/getViewRequest", output = "http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0/GetViewPortType/getViewResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0/GetViewPortType/Fault/standardError")
    })
    public void getView(
        @WebParam(name = "getView", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/interfaces/GetView/1.0", partName = "parameters")
        GetView parameters,
        @WebParam(name = "getViewResponse", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/interfaces/GetView/1.0", mode = WebParam.Mode.OUT, partName = "parameters")
        Holder<GetViewResponse> parameters0,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "timestampHeader")
        Timestamp timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<Signature> signatureHeader,
        @WebParam(name = "PCEHRHeader", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "PCEHRHeader")
        PCEHRHeader pcehrHeader)
        throws StandardErrorMsg
    ;

}
