
package au.net.electronichealth.ns.pcehr.svc.getview._1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getViewService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0", wsdlLocation = "wsdl/B2B_GetView.wsdl")
public class GetViewService
    extends Service
{

    private final static URL GETVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETVIEWSERVICE_EXCEPTION;
    private final static QName GETVIEWSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0", "getViewService");

    static {
        GETVIEWSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.pcehr.svc.getview._1.GetViewService.class.getResource("wsdl/B2B_GetView.wsdl");
        WebServiceException e = null;
        if (GETVIEWSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_GetView.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETVIEWSERVICE_EXCEPTION = e;
    }

    public GetViewService() {
        super(__getWsdlLocation(), GETVIEWSERVICE_QNAME);
    }

    public GetViewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETVIEWSERVICE_QNAME, features);
    }

    public GetViewService(URL wsdlLocation) {
        super(wsdlLocation, GETVIEWSERVICE_QNAME);
    }

    public GetViewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETVIEWSERVICE_QNAME, features);
    }

    public GetViewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetViewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetViewPortType
     */
    @WebEndpoint(name = "getViewSOAP12Port")
    public GetViewPortType getGetViewSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0", "getViewSOAP12Port"), GetViewPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetViewPortType
     */
    @WebEndpoint(name = "getViewSOAP12Port")
    public GetViewPortType getGetViewSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetView/1.0", "getViewSOAP12Port"), GetViewPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETVIEWSERVICE_EXCEPTION!= null) {
            throw GETVIEWSERVICE_EXCEPTION;
        }
        return GETVIEWSERVICE_WSDL_LOCATION;
    }

}
