
package au.net.electronichealth.ns.tplt.svc.searchtemplate._1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "searchTemplateService", targetNamespace = "http://ns.electronichealth.net.au/tplt/svc/SearchTemplate/1.1", wsdlLocation = "wsdl/B2B_SearchTemplate.wsdl")
public class SearchTemplateService
    extends Service
{

    private final static URL SEARCHTEMPLATESERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHTEMPLATESERVICE_EXCEPTION;
    private final static QName SEARCHTEMPLATESERVICE_QNAME = new QName("http://ns.electronichealth.net.au/tplt/svc/SearchTemplate/1.1", "searchTemplateService");

    static {
        SEARCHTEMPLATESERVICE_WSDL_LOCATION = au.net.electronichealth.ns.tplt.svc.searchtemplate._1.SearchTemplateService.class.getResource("wsdl/B2B_SearchTemplate.wsdl");
        WebServiceException e = null;
        if (SEARCHTEMPLATESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_SearchTemplate.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SEARCHTEMPLATESERVICE_EXCEPTION = e;
    }

    public SearchTemplateService() {
        super(__getWsdlLocation(), SEARCHTEMPLATESERVICE_QNAME);
    }

    public SearchTemplateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHTEMPLATESERVICE_QNAME, features);
    }

    public SearchTemplateService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHTEMPLATESERVICE_QNAME);
    }

    public SearchTemplateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHTEMPLATESERVICE_QNAME, features);
    }

    public SearchTemplateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchTemplateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchTemplatePortType
     */
    @WebEndpoint(name = "searchTemplateSOAP12Port")
    public SearchTemplatePortType getSearchTemplateSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/tplt/svc/SearchTemplate/1.1", "searchTemplateSOAP12Port"), SearchTemplatePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchTemplatePortType
     */
    @WebEndpoint(name = "searchTemplateSOAP12Port")
    public SearchTemplatePortType getSearchTemplateSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/tplt/svc/SearchTemplate/1.1", "searchTemplateSOAP12Port"), SearchTemplatePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHTEMPLATESERVICE_EXCEPTION!= null) {
            throw SEARCHTEMPLATESERVICE_EXCEPTION;
        }
        return SEARCHTEMPLATESERVICE_WSDL_LOCATION;
    }

}
