
package au.net.electronichealth.ns.pcehr.svc.getrepresentativelist._1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getRepresentativeListService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/GetRepresentativeList/1.1", wsdlLocation = "wsdl/B2B_GetRepresentativeList.wsdl")
public class GetRepresentativeListService
    extends Service
{

    private final static URL GETREPRESENTATIVELISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETREPRESENTATIVELISTSERVICE_EXCEPTION;
    private final static QName GETREPRESENTATIVELISTSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/svc/GetRepresentativeList/1.1", "getRepresentativeListService");

    static {
        GETREPRESENTATIVELISTSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.pcehr.svc.getrepresentativelist._1.GetRepresentativeListService.class.getResource("wsdl/B2B_GetRepresentativeList.wsdl");
        WebServiceException e = null;
        if (GETREPRESENTATIVELISTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_GetRepresentativeList.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETREPRESENTATIVELISTSERVICE_EXCEPTION = e;
    }

    public GetRepresentativeListService() {
        super(__getWsdlLocation(), GETREPRESENTATIVELISTSERVICE_QNAME);
    }

    public GetRepresentativeListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETREPRESENTATIVELISTSERVICE_QNAME, features);
    }

    public GetRepresentativeListService(URL wsdlLocation) {
        super(wsdlLocation, GETREPRESENTATIVELISTSERVICE_QNAME);
    }

    public GetRepresentativeListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETREPRESENTATIVELISTSERVICE_QNAME, features);
    }

    public GetRepresentativeListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetRepresentativeListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetRepresentativeListPortType
     */
    @WebEndpoint(name = "getRepresentativeListSOAP12Port")
    public GetRepresentativeListPortType getGetRepresentativeListSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetRepresentativeList/1.1", "getRepresentativeListSOAP12Port"), GetRepresentativeListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetRepresentativeListPortType
     */
    @WebEndpoint(name = "getRepresentativeListSOAP12Port")
    public GetRepresentativeListPortType getGetRepresentativeListSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetRepresentativeList/1.1", "getRepresentativeListSOAP12Port"), GetRepresentativeListPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETREPRESENTATIVELISTSERVICE_EXCEPTION!= null) {
            throw GETREPRESENTATIVELISTSERVICE_EXCEPTION;
        }
        return GETREPRESENTATIVELISTSERVICE_WSDL_LOCATION;
    }

}
