
package au.net.electronichealth.ns.pcehr.svc.getauditview._1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getAuditViewService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/GetAuditView/1.1", wsdlLocation = "wsdl/B2B_GetAuditView.wsdl")
public class GetAuditViewService
    extends Service
{

    private final static URL GETAUDITVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETAUDITVIEWSERVICE_EXCEPTION;
    private final static QName GETAUDITVIEWSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/svc/GetAuditView/1.1", "getAuditViewService");

    static {
        GETAUDITVIEWSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.pcehr.svc.getauditview._1.GetAuditViewService.class.getResource("wsdl/B2B_GetAuditView.wsdl");
        WebServiceException e = null;
        if (GETAUDITVIEWSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_GetAuditView.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETAUDITVIEWSERVICE_EXCEPTION = e;
    }

    public GetAuditViewService() {
        super(__getWsdlLocation(), GETAUDITVIEWSERVICE_QNAME);
    }

    public GetAuditViewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETAUDITVIEWSERVICE_QNAME, features);
    }

    public GetAuditViewService(URL wsdlLocation) {
        super(wsdlLocation, GETAUDITVIEWSERVICE_QNAME);
    }

    public GetAuditViewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETAUDITVIEWSERVICE_QNAME, features);
    }

    public GetAuditViewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAuditViewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAuditViewPortType
     */
    @WebEndpoint(name = "getAuditViewSOAP12Port")
    public GetAuditViewPortType getGetAuditViewSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetAuditView/1.1", "getAuditViewSOAP12Port"), GetAuditViewPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAuditViewPortType
     */
    @WebEndpoint(name = "getAuditViewSOAP12Port")
    public GetAuditViewPortType getGetAuditViewSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/GetAuditView/1.1", "getAuditViewSOAP12Port"), GetAuditViewPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETAUDITVIEWSERVICE_EXCEPTION!= null) {
            throw GETAUDITVIEWSERVICE_EXCEPTION;
        }
        return GETAUDITVIEWSERVICE_WSDL_LOCATION;
    }

}
