
package au.net.electronichealth.ns.pcehr.svc.registerpcehr._2;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.PCEHRHeader;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.Signature;
import au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.Timestamp;
import au.net.electronichealth.ns.pcehr.xsd.interfaces.registerpcehr._2.RegisterPCEHR;
import au.net.electronichealth.ns.pcehr.xsd.interfaces.registerpcehr._2.RegisterPCEHRResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegisterPCEHRPortType", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.net.electronichealth.ns.pcehr.xsd.common.commoncoreelements._1.ObjectFactory.class,
    au.net.electronichealth.ns.pcehr.xsd.interfaces.registerpcehr._2.ObjectFactory.class,
    au.net.electronichealth.ns.wsp.xsd.standarderror._2010.ObjectFactory.class,
    pcehr_override.org.w3.ObjectFactory.class
})
public interface RegisterPCEHRPortType {


    /**
     * 
     * @param pcehrHeader
     * @param parameters0
     * @param timestampHeader
     * @param parameters
     * @param signatureHeader
     * @throws StandardErrorMsg
     */
    @WebMethod
    @Action(input = "http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0/RegisterPCEHRPortType/registerPCEHRRequest", output = "http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0/RegisterPCEHRPortType/registerPCEHRResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0/RegisterPCEHRPortType/Fault/standardError")
    })
    public void registerPCEHR(
        @WebParam(name = "registerPCEHR", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/interfaces/RegisterPCEHR/2.0", partName = "parameters")
        RegisterPCEHR parameters,
        @WebParam(name = "registerPCEHRResponse", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/interfaces/RegisterPCEHR/2.0", mode = WebParam.Mode.OUT, partName = "parameters")
        Holder<RegisterPCEHRResponse> parameters0,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "timestampHeader")
        Timestamp timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<Signature> signatureHeader,
        @WebParam(name = "PCEHRHeader", targetNamespace = "http://ns.electronichealth.net.au/pcehr/xsd/common/CommonCoreElements/1.0", header = true, partName = "PCEHRHeader")
        PCEHRHeader pcehrHeader)
        throws StandardErrorMsg
    ;

}
